#version: '3.3'

services:
  postgres_db:
    image: postgres:10.0-alpine
    command: postgres -c 'max_connections=500'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
    restart: always
  yasiu_bot:
    build:
      context: .
      dockerfile: dockerfile_bot
    image: yasiu_bot:latest
    volumes:
      - .:/app
    command: bash -c "python bot/start_bot.py"
    restart: always
