on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  update_ec2:
    runs-on: ubuntu-latest
    steps:           
      - name: "Connect to EC2"
        run: |
          echo ${{secrets.EC2_KEY}} > key.pem
          echo ${secrets.TEST} > TEST.pem
          cat TEST.pem
          ssh -i key.pem ubuntu@${{secrets.EC2_IP}} -y;
      - name: "Stop bot containers"
        run: |
          cd ~/app/discord_bot
          docker-compose down
      - name: "Update bot files"
        run: |
          git pull          
      - name: "Start updated bot"
        run: |
          docker-compose up -d
          exit

