on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  update_ec2:
    runs-on: ubuntu-latest
    steps:           
      - name: "Connect to EC2"
        run: |
          echo "asd" > key.pem
          echo "tttert" > TEST.pem
          cat TEST.pem

