on:
  push:
    branches:
    - master
    paths-ignore:
      - "requirements.txt"
      - "git/*"
  pull_request:
    branches:
    - master
    paths-ignore:
      - "requirements.txt"
      - "git/*"

jobs:
  update_bot_files_on_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: "Connect and update files"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: "ubuntu"
          key: ${{ secrets.EC2_KEY }}
          script:
            whoami;
            cd ~/app/discord_bot;
            docker-compose down;
            git pull;
            docker-compose up -d;
            exit;
