on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  update_ec2:
    runs-on: ubuntu-latest
    steps:           
      - run: |
          ssh -i "$EC2_KEY" ubuntu@"$EC2_IP"
          cd ~/app/discord_bot
          docker-compose down
          git pull
          docker-compose up -d
          exit
          echo "Finished" 
