on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  update_ec2:
    runs-on: ubuntu-latest
    steps:           
      - name: "Connect to EC2"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_KEY }}
          script: whoami
      - name: "Stop bot containers"
        run: |
          cd ~/app/discord_bot
          docker-compose down
      - name: "Update bot files"
        run: |
          git pull          
      - name: "Start updated bot"
        run: |
          docker-compose up -d
          exit

