on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - env:
        IP: ${{ secrets.EC2_IP}}
        KEY: ${{ secrets.EC2_KEY}}
    - run: |
        ssh -i "$KEY" ubuntu@"$IP"
        cd ~/app/discord_bot
        docker-compose down
        git pull
        docker-compose up -d
        exit
        echo "Finished" 
