on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  update_ec2:
    runs-on: ubuntu-latest
    steps:           
      - run: |
          ${secrets.EC2_KEY} > key.pem
          ssh -i key.pem ubuntu@{secrets.EC2_IP} -y
          cd ~/app/discord_bot
          docker-compose down
          git pull
          docker-compose up -d
          exit
          echo "Finished" 
